### ISSUE TITLE
Single units and static weapons don't have correct facing

### ISSUE THREAD

**Issue by astruyk** [SilentSpike/ARMA-SilentMapConverter#11]
They appear to always face north after spawning, even though they have 'setPos ...' being called with what appear to be the correct values from the original mission/editor. Not sure what's up with this. Maybe they aren't initialized or something?

**Comment by astruyk** [comment]
This is fixed by calling the `setFromDir` command in addition to `setDir` for AI (vehicles and units). See the submitted patch.

**Comment by SilentSpike** [comment]
Thanks for the patch (I hadn't noticed it), I was actually just reading about that on the biki.
