### ISSUE TITLE
Ignore gamelogic and units set to playable

### ISSUE THREAD

**Issue by FadiCBB** [SilentSpike/Arma-SilentMapConverter#6]
* Note: this was converted from A3. The differences shouldn't really matter here though.

It would be good if it ignored units set to playable as well as any placed game logic.

Conversion from a mission: [https://dl.dropboxusercontent.com/u/14592975/arma3/Nrth_Comm_Strike_init_HC.sqf](https://dl.dropboxusercontent.com/u/14592975/arma3/Nrth_Comm_Strike_init_HC.sqf)

**Comment by SilentSpike** [comment]
Added in commit 07f05f42bddda2665f850cd206da6ad534bfa955
